/* eslint.config.js — the configuration the `lint` script has always implied.
 *
 * `package.json` declared "lint": "eslint ." from the first frontend commit
 * (0e88788) without ever installing or configuring eslint, so the script has
 * never run. This file, and the devDependencies beside it, make the script
 * true. See issue #254.
 *
 * Deliberately thin. `npm run build` runs `tsc -b` with strict, noUnusedLocals,
 * noUnusedParameters and noFallthroughCasesInSwitch (see tsconfig.json), and
 * that build is the gate CI has always run. Re-implementing those checks here
 * would only create two overlapping rule sets to keep in agreement, which is
 * how lint configs start arguing with the compiler.
 *
 * What tsc structurally cannot check is React hook dependency correctness, and
 * that is the reason this file exists at all: the wizard steps under
 * src/pages/setup already carried `eslint-disable-next-line
 * react-hooks/exhaustive-deps` comments suppressing a rule that had never run.
 *
 * On presets: eslint-plugin-react-hooks `recommended` is NOT the two hook
 * rules. As of v7 it carries the whole React Compiler rule set, 30 rules. That
 * is a separate decision deserving its own issue, so every rule below is named
 * individually rather than extended from a preset. Naming them also keeps this
 * file stable across plugin minor bumps.
 *
 * Everything is an error and unused suppressions are an error, so `eslint .`
 * is a plain pass or fail. A warning nobody has to act on is the same
 * unenforced gate this file was written to retire.
 */

import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import { defineConfig, globalIgnores } from 'eslint/config';

export default defineConfig([
  // node_modules is ignored by eslint itself. `dist` is listed for parity with
  // .gitignore even though vite's outDir is ../Certus.Web/wwwroot, outside this
  // tree. The .ds-* entries are generated by ../../.design-sync/prep.mjs and
  // land at this directory's root; flat config lints dotfiles, so without this
  // a lint run straight after a design-sync prep fails on generated code.
  globalIgnores(['dist/', '.ds-entry.ts', '.ds-compiled.css']),

  {
    linterOptions: {
      // Defaults to 'warn', which would not fail the CI gate. If one of the
      // suppressions in src/pages/setup turns out to be unnecessary now that
      // the rule actually runs, that should break the build and be deleted.
      reportUnusedDisableDirectives: 'error',
    },
  },

  {
    // The three hand-written JS files (tailwind.config.js, postcss.config.js,
    // and this file) are the only sources tsc never sees, so they are the one
    // place the base rules genuinely add cover rather than duplicate it.
    // mjs and cjs are listed so a future config file in either form is covered
    // rather than silently matching no block at all.
    files: ['**/*.{js,mjs,cjs}'],
    extends: [js.configs.recommended],
  },

  {
    // A classic blocking script, deliberately not a module and deliberately not
    // deferred; see the constraints in its own header. Its globals are declared
    // here rather than pulling in the `globals` package for three names.
    files: ['public/theme-init.js'],
    languageOptions: {
      sourceType: 'script',
      globals: {
        document: 'readonly',
        localStorage: 'readonly',
        window: 'readonly',
      },
    },
  },

  {
    // jsx is listed even though the tree is entirely ts and tsx today. Nothing
    // stops a .jsx component being added, tailwind.config.js already scans for
    // one, and a file matching no block at all is linted by zero rules without
    // saying so. That silent hole is the same shape as the problem issue #254
    // exists to close, so the extension list is deliberately wider than the
    // current tree.
    files: ['**/*.{ts,tsx,jsx}'],
    languageOptions: {
      // Parser only. No typescript-eslint rule preset is extended: tsc already
      // owns no-undef, no-unused-vars and the rest of that ground.
      parser: tseslint.parser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'error',
      // allowConstantExport is the Vite setting: exporting a constant beside a
      // component does not defeat fast refresh, exporting a second component
      // does.
      'react-refresh/only-export-components': ['error', { allowConstantExport: true }],
    },
  },
]);
