// <auto-generated />
using System;
using Certus.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Certus.Core.Data.Migrations
{
    [DbContext(typeof(CertusDbContext))]
    [Migration("20260718101813_AddDeviceAttestation")]
    partial class AddDeviceAttestation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("Certus.Core.Data.Entities.AcmeAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EabJwsJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExternalAccountCredentialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JwkJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JwkThumbprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("valid");

                    b.Property<bool>("TermsOfServiceAgreed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("ExternalAccountCredentialId");

                    b.HasIndex("JwkThumbprint")
                        .IsUnique();

                    b.ToTable("AcmeAccounts");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.AcmeAuthorization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttestationFormat")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AttestedPropertiesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttestedSpki")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorizationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifierType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifierValue")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending");

                    b.Property<bool>("Wildcard")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("AcmeAuthorizations");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.AcmeCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdcsRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificatePem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RevokedReason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdcsRequestId");

                    b.HasIndex("CertificateId")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.HasIndex("SerialNumber");

                    b.ToTable("AcmeCertificates");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.AcmeChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttestationObject")
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthorizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChallengeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidationAttempts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ChallengeId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("AcmeChallenges");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.AcmeOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdcsRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CsrDer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifiersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NotAfter")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NotBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("AcmeOrders");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.AlertSent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CertificateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channels")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThresholdDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId", "ThresholdDays")
                        .IsUnique();

                    b.ToTable("AlertsSent");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.AttestationTrustAnchor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificatePem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Format");

                    b.HasIndex("Sha256Fingerprint")
                        .IsUnique();

                    b.ToTable("AttestationTrustAnchors");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.DeviceAllowlistEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifierValue")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "IdentifierValue")
                        .IsUnique();

                    b.ToTable("DeviceAllowlistEntries");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.DeviceAttestationProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CsrIdentifierBinding")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("cn-or-san");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GateMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("allowlist");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId")
                        .IsUnique();

                    b.ToTable("DeviceAttestationProfiles");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.DomainPolicyRejection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectedIdentifiers")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedIdentifiers")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("DomainPolicyRejections");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.EabCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdPrincipalName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdPrincipalSid")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdPrincipalType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NamespacesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretProtected")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SecretRegeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyId")
                        .IsUnique();

                    b.ToTable("EabCredentials");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.SyncedCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotAfter")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NotBefore")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requestor")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RevokedReason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectAlternativeNames")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NotAfter");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("SerialNumber");

                    b.HasIndex("Status");

                    b.HasIndex("Subject");

                    b.HasIndex("TemplateName");

                    b.ToTable("SyncedCertificates");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.AcmeAccount", b =>
                {
                    b.HasOne("Certus.Core.Data.Entities.EabCredential", "ExternalAccountCredential")
                        .WithMany()
                        .HasForeignKey("ExternalAccountCredentialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ExternalAccountCredential");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.AcmeAuthorization", b =>
                {
                    b.HasOne("Certus.Core.Data.Entities.AcmeOrder", "Order")
                        .WithMany("Authorizations")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.AcmeCertificate", b =>
                {
                    b.HasOne("Certus.Core.Data.Entities.AcmeOrder", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.AcmeChallenge", b =>
                {
                    b.HasOne("Certus.Core.Data.Entities.AcmeAuthorization", "Authorization")
                        .WithMany("Challenges")
                        .HasForeignKey("AuthorizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.AcmeOrder", b =>
                {
                    b.HasOne("Certus.Core.Data.Entities.AcmeAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.AlertSent", b =>
                {
                    b.HasOne("Certus.Core.Data.Entities.SyncedCertificate", "Certificate")
                        .WithMany()
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.DeviceAllowlistEntry", b =>
                {
                    b.HasOne("Certus.Core.Data.Entities.DeviceAttestationProfile", "Profile")
                        .WithMany("AllowlistEntries")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.AcmeAuthorization", b =>
                {
                    b.Navigation("Challenges");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.AcmeOrder", b =>
                {
                    b.Navigation("Authorizations");
                });

            modelBuilder.Entity("Certus.Core.Data.Entities.DeviceAttestationProfile", b =>
                {
                    b.Navigation("AllowlistEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
